fn main() {
    println!("Hello, world!");
}

#[test]
fn test_fail() {
    panic!("Une erreur");
}